services: 
  steam-cmd: 
    build: 
      context: ./steamcmd/debian
      dockerfile: Dockerfile 
      target: steam-cmd
    restart: always
    image: harbor.ops.mcclory.io/games/base/steamcmd:root
    pull_policy: always 
  source:
    build: 
      context: ./games/source
      dockerfile: Dockerfile
      target: source
    restart: always
    depends_on: 
      - steam-cmd
    image: harbor.ops.mcclory.io/games/base/steamcmd:latest 
    pull_policy: always
  source-metamod: 
    build: 
      context: ./games/source
      dockerfile: Dockerfile
      target:  source-metamod
    restart: always
    depends_on: 
      - source
    image: harbor.ops.mcclory.io/games/base/source:metamod 
    pull_policy: always
  source-sourcemod: 
    build: 
      context: ./games/source 
      dockerfile: Dockerfile 
      target: source-metamod
    depends_on: 
      - source-metamod
    restart: always
    image: harbor.ops.mcclory.io/games/base/source:sourcemod 
    pull_policy: always
  csgo-base: 
    build: 
      context: ./games/csgo
      dockerfile: Dockerfile
      target: csgo
    restart: always
    depends_on: 
      - source
    image: harbor.ops.mcclory.io/games/csgo:latest 
    pull_policy: always
  csgo-metamod: 
    build: 
      context: ./games/csgo
      dockerfile: Dockerfile
      target: csgo-metamod
    restart: always
    depends_on: 
      - csgo-base
    image: harbor.ops.mcclory.io/games/csgo:metamod 
    pull_policy: always
  csgo-sourcemod:
    build: 
      context: ./games/csgo
      dockerfile: Dockerfile
      target: csgo-sourcemod
    restart: always
    depends_on: 
      - csgo-metamod
    image: harbor.ops.mcclory.io/games/csgo:sourcemod 
    pull_policy: always